BIN = vendor/bin

test:
	@$(BIN)/phpunit tests
lint:
	@$(BIN)/phpcs
lint-fix:
	@$(BIN)/phpcbf
drone:
	@echo "############################################"   >  .drone.yml
	@echo "# /!\\ DO NOT EDIT THIS FILE MANUALLY /!\\   #" >> .drone.yml
	@echo "# ---------------------------------------- #"   >> .drone.yml
	@echo "#   1. Edit .drone.jsonnet file instead    #"   >> .drone.yml
	@echo "#   2. Install Drone CLI:                  #"   >> .drone.yml
	@echo "#      https://docs.drone.io/cli/install/  #"   >> .drone.yml
	@echo "#   3. Run: make drone                     #"   >> .drone.yml
	@echo "#   4. Commit .drone.yml file              #"   >> .drone.yml
	@echo "############################################"   >> .drone.yml
	@drone jsonnet --stream --stdout                       >> .drone.yml
	@echo "Success! .drone.yml file has been updated based on jsonnet syntax."
